### ISSUE TITLE
Finish Presentation - Oberseminar

### ISSUE THREAD

**Issue by marc101101** [marc101101/masterarbeit_eye_tracking#3]
**Drive:**
https://docs.google.com/presentation/d/1xPIJZ2bL-hntchO5ANkjUwOBVA0qE33xz5utlu3YqHg/edit?usp=drivesdk

**ToDo:**
- [x] Passt "Motivation und Relevanz" so in dieser grafischen Darstellung
- [x] Fokus im "Related Work"? 
- [x] To-Do/Clarify Punkt?
